/**
 * TODO - This file was generated by Claude and requires comprehensive manual review.
 */

import type { ElementMap, InputOptions, ValidInput } from './Input'
import type { State } from '../shared/state'
import type { Folder } from '../Folder'

import { create } from '../shared/create'
import { Logger } from '../shared/logger'
import { state } from '../shared/state'
import { Input } from './Input'

export type ArrayInputOptions<T = any> = InputOptions<T[]> & {
	readonly __type?: 'ArrayInputOptions'
	/**
	 * The maximum number of items to display before collapsing.
	 * @default 20
	 */
	maxItems?: number
	/**
	 * Whether the array folder should be closed by default.
	 * @default true
	 */
	closed?: boolean
}

export const ARRAY_INPUT_DEFAULTS = {
	__type: 'ArrayInputOptions' as const,
	value: [],
	maxItems: 20,
	closed: true,
} as const satisfies ArrayInputOptions

export interface ArrayControllerElements extends ElementMap {
	container: HTMLElement
	content: HTMLElement
}

export class InputArray<T = any> extends Input<T[], ArrayInputOptions<T>, ArrayControllerElements> {
	readonly __type = 'InputArray' as const
	readonly initialValue: T[]
	readonly state: State<T[]>

	/**
	 * The internal folder that contains the individual array item inputs.
	 */
	folder: Folder

	/**
	 * Individual inputs for each array item.
	 */
	items: ValidInput[] = []

	#log: Logger

	constructor(options: Partial<ArrayInputOptions<T>>, folder: Folder) {
		const opts = Object.assign({}, ARRAY_INPUT_DEFAULTS, options)
		super(opts, folder)

		this.#log = new Logger(`InputArray ${opts.title}`, { fg: 'purple' })
		this.#log.fn('constructor').debug({ opts, this: this })

		if (opts.binding) {
			this.initialValue = opts.binding.target[opts.binding.key]
			this.state = state(this.initialValue)

			this._evm.add(
				this.state.subscribe(v => {
					opts.binding!.target[opts.binding!.key] = v
				}),
			)
		} else {
			this.initialValue = opts.value!
			this.state = state(opts.value!)
		}

		// Create internal folder for array items
		this.folder = folder.addFolder(opts.title || 'Array', {
			closed: opts.closed,
		})

		this.elements.container = create('div', {
			classes: ['gooey-input-array-container'],
			parent: this.elements.content,
		})

		this.elements.content = this.folder.elements.content

		// Initialize array items
		this._createArrayItems()

		this._evm.add(
			this.state.subscribe(() => {
				this.refresh()
			}),
		)
	}

	private _createArrayItems(): void {
		const array = this.state.value
		this.items = []

		for (let i = 0; i < array.length; i++) {
			const item = array[i]
			const input = this._createItemInput(i, item)
			this.items.push(input)
		}
	}

	private _createItemInput(index: number, value: T): ValidInput {
		// Create input based on the type of the value
		// Use empty string as title for full-width display
		const title = ''
		
		// Create inputs without binding - we'll handle the binding manually
		if (typeof value === 'boolean') {
			const input = this.folder.addSwitch(title, value)
			input.on('change', (newValue) => this._updateArrayItem(index, newValue))
			return input
		} else if (typeof value === 'number') {
			const input = this.folder.addNumber(title, value)
			input.on('change', (newValue) => this._updateArrayItem(index, newValue))
			return input
		} else if (typeof value === 'string') {
			const input = this.folder.addText(title, value)
			input.on('change', (newValue) => this._updateArrayItem(index, newValue))
			return input
		} else if (typeof value === 'object' && value !== null) {
			// For objects, create a nested structure
			const input = this.folder.addText(title, JSON.stringify(value))
			input.on('change', (newValue) => {
				try {
					this._updateArrayItem(index, JSON.parse(newValue))
				} catch {
					// If JSON parsing fails, keep as string
					this._updateArrayItem(index, newValue as any)
				}
			})
			return input
		} else {
			// Fallback: text representation
			const input = this.folder.addText(title, String(value))
			input.on('change', (newValue) => this._updateArrayItem(index, newValue as any))
			return input
		}
	}

	private _updateArrayItem(index: number, newValue: any): void {
		const currentArray = [...this.state.value]
		currentArray[index] = newValue
		
		// Update the original binding target if it exists
		if (this.opts.binding) {
			this.opts.binding.target[this.opts.binding.key] = currentArray
		}
		
		// Update our state without triggering refresh
		this.state.set(currentArray)
		this.emit('change', currentArray)
	}

	set = (v: T[]): this => {
		this.state.set(v)
		this._recreateItems()
		this.emit('change', v)
		return this
	}

	private _recreateItems(): void {
		// Clear existing items
		for (const item of this.items) {
			item.dispose()
		}
		this.items = []
		this.folder.inputs.clear()

		// Recreate items with new values
		this._createArrayItems()
	}

	refresh = (): this => {
		const currentArray = this.state.value
		
		// Update the array from individual item values
		const newArray = this.items.map(item => item.value) as T[]
		
		// Check if array has changed (avoid infinite loop)
		if (JSON.stringify(currentArray) !== JSON.stringify(newArray)) {
			// Update the original binding target if it exists, not our state
			if (this.opts.binding) {
				this.opts.binding.target[this.opts.binding.key] = newArray
			}
		}

		super.refresh(currentArray)
		return this
	}

	dispose(): void {
		for (const item of this.items) {
			item.dispose()
		}
		this.folder.dispose()
		super.dispose()
	}
}
