import type { GooeyPreset } from '../../../../../src/Gooey'

// todo - migrate these to the new format

export const ORBS_PRESETS = [
	{
		__type: 'GooeyPreset',
		__version: 0,
		id: 'gooey-default-preset',
		title: 'default',
		data: {
			__type: 'FolderPreset',
			id: 'Orbs',
			title: 'Orbs',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'Orbs__base',
					title: 'base',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'count',
							value: 50,
							disabled: false,
							presetId: 'Orbs__base__count',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'width',
							value: 213,
							disabled: false,
							presetId: 'Orbs__base__width',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'height',
							value: 120,
							disabled: false,
							presetId: 'Orbs__base__height',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'Orbs__motion',
					title: 'motion',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.02,
							disabled: false,
							presetId: 'Orbs__motion__speed',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'force x',
							value: 1,
							disabled: false,
							presetId: 'Orbs__motion__force x',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'force y',
							value: 1,
							disabled: false,
							presetId: 'Orbs__motion__force y',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'temporal drift',
							value: 0,
							disabled: false,
							presetId: 'Orbs__motion__temporal drift',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'SwitchInputOptions',
							title: 'modulate',
							value: true,
							disabled: false,
							presetId: 'Orbs__motion__modulate',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'Orbs__appearance',
					title: 'appearance',
					hidden: false,
					children: [
						{
							__type: 'FolderPreset',
							id: 'Orbs__appearance__glow',
							title: 'glow',
							hidden: false,
							children: [],
							inputs: [
								{
									__type: 'NumberInputOptions',
									title: 'glowR',
									value: 10,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowR',
									hidden: false,
									order: 0,
									resettable: true,
								},
								{
									__type: 'NumberInputOptions',
									title: 'glowG',
									value: 10,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowG',
									hidden: false,
									order: 0,
									resettable: true,
								},
								{
									__type: 'NumberInputOptions',
									title: 'glowB',
									value: 50,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowB',
									hidden: false,
									order: 0,
									resettable: true,
								},
							],
						},
					],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 5,
							disabled: false,
							presetId: 'Orbs__appearance__size',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'floop',
							value: 0.01,
							disabled: false,
							presetId: 'Orbs__appearance__floop',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'brightness',
							value: 0.4,
							disabled: false,
							presetId: 'Orbs__appearance__brightness',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#0acafaff',
							disabled: false,
							presetId: 'Orbs__appearance__color',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'ColorInputOptions',
							title: 'accent',
							value: '#003263ff',
							disabled: false,
							presetId: 'Orbs__appearance__accent',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: 0,
		id: 'nbaoNULZ3bblukz15sxzH',
		title: 'spicy cheese floops',
		data: {
			__type: 'FolderPreset',
			id: 'Orbs',
			title: 'Orbs',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'Orbs__base',
					title: 'base',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'count',
							value: 102,
							disabled: false,
							presetId: 'Orbs__base__count',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'width',
							value: 213,
							disabled: false,
							presetId: 'Orbs__base__width',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'height',
							value: 120,
							disabled: false,
							presetId: 'Orbs__base__height',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'Orbs__motion',
					title: 'motion',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.02,
							disabled: false,
							presetId: 'Orbs__motion__speed',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'force x',
							value: 1,
							disabled: false,
							presetId: 'Orbs__motion__force x',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'force y',
							value: 1,
							disabled: false,
							presetId: 'Orbs__motion__force y',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'temporal drift',
							value: 0,
							disabled: false,
							presetId: 'Orbs__motion__temporal drift',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'SwitchInputOptions',
							title: 'modulate',
							value: true,
							disabled: false,
							presetId: 'Orbs__motion__modulate',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'Orbs__appearance',
					title: 'appearance',
					hidden: false,
					children: [
						{
							__type: 'FolderPreset',
							id: 'Orbs__appearance__glow',
							title: 'glow',
							hidden: false,
							children: [],
							inputs: [
								{
									__type: 'NumberInputOptions',
									title: 'glowR',
									value: 6.03,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowR',
									hidden: false,
									order: 0,
									resettable: true,
								},
								{
									__type: 'NumberInputOptions',
									title: 'glowG',
									value: 0,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowG',
									hidden: false,
									order: 0,
									resettable: true,
								},
								{
									__type: 'NumberInputOptions',
									title: 'glowB',
									value: 20,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowB',
									hidden: false,
									order: 0,
									resettable: true,
								},
							],
						},
					],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 5,
							disabled: false,
							presetId: 'Orbs__appearance__size',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'floop',
							value: 0.28,
							disabled: false,
							presetId: 'Orbs__appearance__floop',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'brightness',
							value: 0.58,
							disabled: false,
							presetId: 'Orbs__appearance__brightness',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#fa460aff',
							disabled: false,
							presetId: 'Orbs__appearance__color',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'ColorInputOptions',
							title: 'accent',
							value: '#630002ff',
							disabled: false,
							presetId: 'Orbs__appearance__accent',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: 0,
		id: 'V1oU2TcKW1Ps4rFY5ZpZE',
		title: 'raver',
		data: {
			__type: 'FolderPreset',
			id: 'Orbs',
			title: 'Orbs',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'Orbs__base',
					title: 'base',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'count',
							value: 113,
							disabled: false,
							presetId: 'Orbs__base__count',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'width',
							value: 213,
							disabled: false,
							presetId: 'Orbs__base__width',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'height',
							value: 120,
							disabled: false,
							presetId: 'Orbs__base__height',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'Orbs__motion',
					title: 'motion',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.0784,
							disabled: false,
							presetId: 'Orbs__motion__speed',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'force x',
							value: 0.547,
							disabled: false,
							presetId: 'Orbs__motion__force x',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'force y',
							value: 1,
							disabled: false,
							presetId: 'Orbs__motion__force y',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'temporal drift',
							value: 0.691,
							disabled: false,
							presetId: 'Orbs__motion__temporal drift',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'SwitchInputOptions',
							title: 'modulate',
							value: true,
							disabled: false,
							presetId: 'Orbs__motion__modulate',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'Orbs__appearance',
					title: 'appearance',
					hidden: false,
					children: [
						{
							__type: 'FolderPreset',
							id: 'Orbs__appearance__glow',
							title: 'glow',
							hidden: false,
							children: [],
							inputs: [
								{
									__type: 'NumberInputOptions',
									title: 'glowR',
									value: 9.94,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowR',
									hidden: false,
									order: 0,
									resettable: true,
								},
								{
									__type: 'NumberInputOptions',
									title: 'glowG',
									value: 13.53,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowG',
									hidden: false,
									order: 0,
									resettable: true,
								},
								{
									__type: 'NumberInputOptions',
									title: 'glowB',
									value: 20,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowB',
									hidden: false,
									order: 0,
									resettable: true,
								},
							],
						},
					],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 1,
							disabled: false,
							presetId: 'Orbs__appearance__size',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'floop',
							value: 0.001,
							disabled: false,
							presetId: 'Orbs__appearance__floop',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'brightness',
							value: 0.64,
							disabled: false,
							presetId: 'Orbs__appearance__brightness',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#0a16faff',
							disabled: false,
							presetId: 'Orbs__appearance__color',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'ColorInputOptions',
							title: 'accent',
							value: '#00ff51ff',
							disabled: false,
							presetId: 'Orbs__appearance__accent',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: 0,
		id: 'Htcxi_Wk0wyRtiQh5SDo3',
		title: 'space banana',
		data: {
			__type: 'FolderPreset',
			id: 'Orbs',
			title: 'Orbs',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'Orbs__base',
					title: 'base',
					// closed: true,
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'count',
							value: 50,
							disabled: false,
							presetId: 'Orbs__base__count',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'width',
							value: 213,
							disabled: false,
							presetId: 'Orbs__base__width',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'height',
							value: 120,
							disabled: false,
							presetId: 'Orbs__base__height',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'Orbs__motion',
					title: 'motion',
					// closed: true,
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.02,
							disabled: false,
							presetId: 'Orbs__motion__speed',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'force x',
							value: 1,
							disabled: false,
							presetId: 'Orbs__motion__force x',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'force y',
							value: 1,
							disabled: false,
							presetId: 'Orbs__motion__force y',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'temporal drift',
							value: 0,
							disabled: false,
							presetId: 'Orbs__motion__temporal drift',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'SwitchInputOptions',
							title: 'modulate',
							value: true,
							disabled: false,
							presetId: 'Orbs__motion__modulate',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'Orbs__appearance',
					title: 'appearance',
					hidden: false,
					children: [
						{
							__type: 'FolderPreset',
							id: 'Orbs__appearance__glow',
							title: 'glow',
							// closed: true,
							hidden: false,
							children: [],
							inputs: [
								{
									__type: 'NumberInputOptions',
									title: 'glowR',
									value: 10,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowR',
									hidden: false,
									order: 0,
									resettable: true,
								},
								{
									__type: 'NumberInputOptions',
									title: 'glowG',
									value: 10,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowG',
									hidden: false,
									order: 0,
									resettable: true,
								},
								{
									__type: 'NumberInputOptions',
									title: 'glowB',
									value: 50,
									disabled: false,
									presetId: 'Orbs__appearance__glow__glowB',
									hidden: false,
									order: 0,
									resettable: true,
								},
							],
						},
					],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 24,
							disabled: false,
							presetId: 'Orbs__appearance__size',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'floop',
							value: 0.019,
							disabled: false,
							presetId: 'Orbs__appearance__floop',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'brightness',
							value: 0.4,
							disabled: false,
							presetId: 'Orbs__appearance__brightness',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#cefa0aff',
							disabled: false,
							presetId: 'Orbs__appearance__color',
							hidden: false,
							order: 0,
							resettable: true,
						},
						{
							__type: 'ColorInputOptions',
							title: 'accent',
							value: '#007fffff',
							disabled: false,
							presetId: 'Orbs__appearance__accent',
							hidden: false,
							order: 0,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	} as const satisfies GooeyPreset,
] as const satisfies GooeyPreset[]
