import type { GooeyPreset } from '../../../../../src/Gooey'

const presets: GooeyPreset[] = [
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: 'gooey-default-preset',
		title: 'default',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#9757ffff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 263,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 1.22,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 11.2,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.0123,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 1,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'fractalNoise',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.66,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: 'U3JDeBFa4VnfnaeXuszvC',
		title: 'wet scarf',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#ff57e3ff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 310,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 1.43,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 25,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.0376,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 1,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'fractalNoise',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.18,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: '8r2nG29SgKL9-QdyL3V3j',
		title: 'static',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#5773ffff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 230,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 0.5,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 4.6,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.5,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 2,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'fractalNoise',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.91,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: 'QlDhuBQTGZPtt6rQK82-M',
		title: 'glop',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#57d8ffff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 194,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 0.77,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 27.4,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.0042,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 9,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'turbulence',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.77,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: 'Fvx4SpI9rMjyUzaYpWmFp',
		title: 'unagi',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#5aff57ff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 119,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 2.68,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 100,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.0155,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 1,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'fractalNoise',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.7,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: 'J7gfa1wxlenPAlaxbi6bo',
		title: 'solar winds',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#e9ff57ff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 68,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 1.89,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 32,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.0272,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 8,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'fractalNoise',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.3,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: 'lhsmhBe0x-waMQGKFnMJf',
		title: 'underwater',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#ff5757ff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 360,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 0.5,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 5.3,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.0272,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 2,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'fractalNoise',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 1,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: '_wVMWhdw3zRL7oDkpNf74',
		title: 'mist',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#9757ffff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 263,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 1,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 38.3,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.5,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 20,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'turbulence',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.18,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: 'HbtI0SosIN4lFeX0pcXgx',
		title: 'dried paint',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#ff5757ff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 0,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 1,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 38.3,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.0535,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 20,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'turbulence',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.18,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: 'zCb8rhhzHLqO7LRaII3ih',
		title: 'alien graffiti',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#57b9ffff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 205,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 1,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 100,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.0155,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 1,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'turbulence',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.63,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: 'tu8nkAVDEAL-ypJTVUOTF',
		title: 'jungle',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#57f4ffff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 184,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 0.5,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 52.4,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.1038,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 1,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'turbulence',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.1,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
	{
		__type: 'GooeyPreset',
		__version: '2',
		id: 'G2woObSfl2ZLAVC-5UDQx',
		title: 'ghost flame',
		data: {
			__type: 'FolderPreset',
			id: 'gooey',
			title: 'gooey',
			hidden: false,
			children: [
				{
					__type: 'FolderPreset',
					id: 'gooey__orbs',
					title: 'orbs',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'ColorInputOptions',
							title: 'color',
							value: '#ffdb57ff',
							disabled: false,
							presetId: 'gooey__orbs__color',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'hue',
							value: 47,
							disabled: false,
							presetId: 'gooey__orbs__hue',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'size',
							value: 0.92,
							disabled: false,
							presetId: 'gooey__orbs__size',
							hidden: false,
							order: 3,
							resettable: true,
						},
					],
				},
				{
					__type: 'FolderPreset',
					id: 'gooey__goo',
					title: 'goo',
					hidden: false,
					children: [],
					inputs: [
						{
							__type: 'NumberInputOptions',
							title: 'gooeyness',
							value: 13,
							disabled: false,
							presetId: 'gooey__goo__gooeyness',
							hidden: false,
							order: 1,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'viscosity',
							value: 0.0365,
							disabled: false,
							presetId: 'gooey__goo__viscosity',
							hidden: false,
							order: 2,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'density',
							value: 9,
							disabled: false,
							presetId: 'gooey__goo__density',
							hidden: false,
							order: 3,
							resettable: true,
						},
						{
							__type: 'SelectInputOptions',
							title: 'texture',
							value: 'turbulence',
							disabled: false,
							presetId: 'gooey__goo__texture',
							hidden: false,
							order: 4,
							resettable: true,
						},
						{
							__type: 'NumberInputOptions',
							title: 'speed',
							value: 0.66,
							disabled: false,
							presetId: 'gooey__goo__speed',
							hidden: false,
							order: 5,
							resettable: true,
						},
					],
				},
			],
			inputs: [],
		},
	},
]

export default presets
